kind: pipeline
name: linux-arm
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 400MiB
    limits:
      cpu: 1000
      memory: 400MiB
  settings:
    repo: ikaruswill/leantime
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

