kind: pipeline
name: linux-arm
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: checkout arm dockerfile
  image: ikaruswill/git
  commands:
  - git fetch --no-tags origin ikaruswill/arm-docker:refs/remotes/origin/ikaruswill/arm-docker
  - git checkout origin/ikaruswill/arm-docker docker/Dockerfile.flux.arm

- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 1500
      memory: 300MiB
    limits:
      cpu: 1500
      memory: 300MiB
  settings:
    repo: ${DRONE_REPO}
    context: docker/
    dockerfile: docker/Dockerfile.flux.arm
    auto_tag: true
    auto_tag_suffix: linux-arm
    build_args:
    - FLUX_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/v*
    - refs/tags/helm-*
    - refs/tags/chart-*
    - refs/tags/master-*

---
kind: pipeline
name: linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: checkout arm dockerfile
  image: ikaruswill/git
  commands:
  - git fetch --no-tags origin ikaruswill/arm-docker:refs/remotes/origin/ikaruswill/arm-docker
  - git checkout origin/ikaruswill/arm-docker docker/Dockerfile.flux.arm

- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 1500
      memory: 300MiB
    limits:
      cpu: 1500
      memory: 300MiB
  settings:
    repo: ${DRONE_REPO}
    context: docker/
    dockerfile: docker/Dockerfile.flux.arm
    auto_tag: true
    auto_tag_suffix: linux-arm64
    build_args:
    - FLUX_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/v*
    - refs/tags/helm-*
    - refs/tags/chart-*
    - refs/tags/master-*

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: ${DRONE_REPO_NAME}
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm
    - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/v*
    - refs/tags/helm-*
    - refs/tags/chart-*
    - refs/tags/master-*

depends_on:
- linux-arm
- linux-arm64

