kind: pipeline
name: fe-linux-arm
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/fluxweb-frontend
    context: frontend/
    dockerfile: frontend/Dockerfile
    auto_tag: true
    auto_tag_suffix: linux-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: fe-linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/fluxweb-frontend
    context: frontend/
    dockerfile: frontend/Dockerfile
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: fe-manifests
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: fluxweb-frontend
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm
    - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- fe-linux-arm
- fe-linux-arm64

---
kind: pipeline
name: be-linux-arm
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/fluxweb-backend
    context: backend/
    dockerfile: backend/Dockerfile
    auto_tag: true
    auto_tag_suffix: linux-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: be-linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/fluxweb-backend
    context: backend/
    dockerfile: backend/Dockerfile
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: be-manifests
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: fluxweb-backend
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm
    - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- be-linux-arm
- be-linux-arm64

