kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: build frontend
  image: node:latest
  commands:
  - cd ui && npm install && npm run build
  resources:
    requests:
      cpu: 100
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB

- name: build backend
  image: golang:latest
  environment:
    GOOS: linux
    GOARCH: arm64
    # GOARM: '7'
  commands:
  - go get github.com/go-bindata/go-bindata/...
  - go get github.com/elazarl/go-bindata-assetfs/...
  - go-bindata-assetfs -prefix ui/dist ui/dist
  - go build .
  resources:
    requests:
      cpu: 100
      memory: 200MiB
    limits:
      cpu: 1000
      memory: 200MiB

- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 100
      memory: 100MiB
    limits:
      cpu: 100
      memory: 100MiB
  settings:
    repo: ${DRONE_REPO}
    dockerfile: Dockerfile.prebuilt
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password
