kind: pipeline
name: build docker (linux-arm64)
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 100
      memory: 100MiB
    limits:
      cpu: 1000
      memory: 100MiB
  settings:
    repo: ikaruswill/glibc-builder
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master

---
kind: pipeline
name: build docker (linux-amd64)
type: kubernetes

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 100
      memory: 100MiB
    limits:
      cpu: 1000
      memory: 100MiB
  settings:
    repo: ikaruswill/glibc-builder
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: amd64

trigger:
  ref:
  - refs/heads/master

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: glibc-builder
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm64
    - linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master

depends_on:
- build docker (linux-arm64)
- build docker (linux-amd64)

---
kind: pipeline
name: build release (linux-arm64)
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: build
  image: ikaruswill/glibc-builder
  pull: always
  environment:
    GLIBC_VERSION: ${DRONE_TAG%%-0}
    STDOUT: 1
  resources:
    requests:
      cpu: 1000
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  commands:
  - cd /
  - /builder > /drone/src/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz
  

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_public_token
    files:
    - glibc-bin-*
    checksum:
    - sha512
    note: '[The GNU C Library](https://www.gnu.org/software/libc/), version ${DRONE_TAG%%-0}.'

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/tags/*

---
kind: pipeline
name: build release (linux-amd64)
type: kubernetes

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: ikaruswill/glibc-builder
  pull: always
  environment:
    GLIBC_VERSION: ${DRONE_TAG%%-0}
    STDOUT: 1
  resources:
    requests:
      cpu: 1000
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  commands:
  - cd /
  - /builder > /drone/src/glibc-bin-$GLIBC_VERSION-0-$(uname -m).tar.gz

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_public_token
    files:
    - glibc-bin-*
    checksum:
    - sha512
    note: '[The GNU C Library](https://www.gnu.org/software/libc/), version ${DRONE_TAG%%-0}.'

node_selector:
  kubernetes.io/arch: amd64

trigger:
  ref:
  - refs/tags/*

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password
---
kind: secret
name: github_release_public_token
get:
  path: drone-secrets
  name: github_release_public_token