kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: ikaruswill/git
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
  - tag
  - push

---

kind: pipeline
name: master-push
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: sync-upsteam-tags
  image: ikaruswill/git
  commands:
  - git remote add upstream https://github.com/alpine-docker/git.git
  - git fetch upstream
  - git push --tags origin

trigger:
  branch:
  - master
  event:
  - push
