kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 500
      memory: 100MiB
    limits:
      cpu: 500
      memory: 100MiB
  settings:
    repo: ikaruswill/git
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
  - tag
  - push
