kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: checkout-arm-docker
  image: ikaruswill/git
  commands:
  - git fetch
  - git checkout ikaruswill/arm-docker
  - git merge $DRONE_COMMIT --no-edit --strategy-option theirs

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1450
  resources:
    requests:
      cpu: 1500
      memory: 300MiB
    limits:
      cpu: 1500
      memory: 300MiB
  settings:
    repo: ikaruswill/flux
    context: docker/
    dockerfile: docker/Dockerfile.flux.arm
    auto_tag: true
    build_args:
    - FLUX_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
node_selector:
  kubernetes.io/arch: arm
trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/v*
    - refs/tags/helm-*
    - refs/tags/chart-*
    - refs/tags/master-*

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password