kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: checkout arm dockerfile
  image: ikaruswill/git
  commands:
  - git fetch --no-tags origin ikaruswill/arm-docker:refs/remotes/origin/ikaruswill/arm-docker
  - git checkout origin/ikaruswill/arm-docker docker/Dockerfile.flux.arm

- name: patch client.go
  image: ikaruswill/git
  commands:
  - git fetch --no-tags origin ikaruswill/multiarch-fix:refs/remotes/origin/ikaruswill/multiarch-fix
  - git checkout origin/ikaruswill/multiarch-fix pkg/registry/client.go

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 1500
      memory: 300MiB
    limits:
      cpu: 1500
      memory: 300MiB
  settings:
    repo: ikaruswill/flux
    context: docker/
    dockerfile: docker/Dockerfile.flux.arm
    auto_tag: true
    build_args:
    - FLUX_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
node_selector:
  kubernetes.io/arch: arm
trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/v*
    - refs/tags/helm-*
    - refs/tags/chart-*
    - refs/tags/master-*

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password