kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: checkout-arm-docker
  image: ikaruswill/git
  commands:
  - git fetch
  - git checkout ikaruswill/arm-docker
  - git merge $DRONE_COMMIT --no-edit --strategy-option theirs

- name: publish
  image: plugins/docker
  resources:
    requests:
      cpu: 1000
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/gitea
    auto_tag: true
    dockerfile: Dockerfile.arm
    build_args:
    - GITEA_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - tag

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password