kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: checkout-arm-docker-1.10
  image: ikaruswill/git
  commands:
  - git fetch origin ikaruswill/arm-docker-1.10
  - git checkout ikaruswill/arm-docker-1.10
  - git merge $DRONE_COMMIT --no-edit --strategy-option theirs
  when:
    ref:
    - refs/tags/v1.10.*

- name: checkout-arm-docker-1.11
  image: ikaruswill/git
  commands:
  - git fetch origin ikaruswill/arm-docker-1.11
  - git checkout ikaruswill/arm-docker-1.11
  - git merge $DRONE_COMMIT --no-edit --strategy-option theirs
  when:
    ref:
    - refs/tags/v1.11.*

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 1000
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ikaruswill/gitea
    auto_tag: true
    dockerfile: Dockerfile.arm
    build_args:
    - GITEA_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
node_selector:
  kubernetes.io/arch: arm
trigger:
  ref:
  - refs/tags/*

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password