kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

steps:
- name: checkout-arm-docker
  image: ikaruswill/git
  commands:
  - git fetch
  - git checkout ikaruswill/arm-docker
  - git merge origin/master --no-edit

- name: publish
  image: plugins/docker
  settings:
    repo: ikaruswill/gitea
    auto_tag: true
    dockerfile: Dockerfile.arm
    build_args:
    - GITEA_VERSION=${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - tag
