kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: build
  image: golang:1.13
  commands:
  - make build-local
  resources:
    requests:
      cpu: 1000
      memory: 300MiB
    limits:
      cpu: 1000
      memory: 300MiB

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1450
  resources:
    requests:
      cpu: 100
      memory: 100MiB
    limits:
      cpu: 100
      memory: 100MiB
  settings:
    repo: ikaruswill/kube-state-metrics
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password