kind: pipeline
name: linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

resources:
  requests:
    cpu: 500
    memory: 200MiB

steps:
- name: publish
  image: plugins/docker
  resources:
    limits:
      cpu: 1000
      memory: 300MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    build_args:
    - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db?pgbouncer=true
    - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/main
  - refs/tags/*

---
kind: pipeline
name: linux-amd64
type: kubernetes

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

resources:
  requests:
    cpu: 500
    memory: 300MiB

steps:
- name: publish
  image: plugins/docker
  resources:
    limits:
      cpu: 1000
      memory: 200MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-amd64
    build_args:
    - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db?pgbouncer=true
    - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: amd64

trigger:
  ref:
  - refs/heads/main
  - refs/tags/*

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: ${DRONE_REPO_NAME}
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/main/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest:1.4
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm64
    - linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/main
  - refs/tags/*

depends_on:
- linux-arm64
- linux-amd64

