kind: pipeline
name: linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

resources:
  requests:
    cpu: 1000
    memory: 300MiB

steps:
- name: get dockerfile
  image: alpine/git
  commands:
  - git fetch --no-tags origin ikaruswill/Dockerfile:refs/remotes/origin/ikaruswill/Dockerfile
  - git checkout origin/ikaruswill/Dockerfile Dockerfile

- name: publish
  image: plugins/docker
  resources:
    limits:
      cpu: 1500
      memory: 400MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: linux-amd64
type: kubernetes

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

resources:
  requests:
    cpu: 500
    memory: 300MiB

steps:
- name: get dockerfile
  image: alpine/git
  commands:
  - git fetch --no-tags origin ikaruswill/Dockerfile:refs/remotes/origin/ikaruswill/Dockerfile
  - git checkout origin/ikaruswill/Dockerfile Dockerfile

- name: publish
  image: plugins/docker
  resources:
    limits:
      cpu: 1000
      memory: 400MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: amd64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: ${DRONE_REPO_NAME}
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm64
    - linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- linux-arm64
- linux-amd64

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password