kind: pipeline
name: linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: build
  image: rust:1.46
  resources:
    requests:
      cpu: 1000
      memory: 200MiB
    limits:
      cpu: 2000
      memory: 200MiB
  commands:
  - USER=root cargo new --bin vaultwarden_ldap
  - cd vaultwarden_ldap
  - cp ../Cargo.toml ../Cargo.lock ./
  - cargo build --locked --release
  - rm ./target/release/deps/vaultwarden_ldap*
  - cp -r ../src src
  - cargo build --release
  - cp target/release/vaultwarden_ldap ../vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
  - sha512sum ../vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH} > ../sha512sum-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.txt

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_public_token
    files:
    - vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    - sha512sum-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.txt
    title: ${DRONE_TAG}
    note: 'LDAP addon for Vaultwarden, version ${DRONE_TAG}'
  when:
    ref:
    - refs/tags/*

- name: checkout custom dockerfile
  image: ikaruswill/git
  commands:
  - git fetch --no-tags origin ikaruswill/arm-docker:refs/remotes/origin/ikaruswill/arm-docker
  - git checkout origin/ikaruswill/arm-docker Dockerfile_custom

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: Dockerfile_custom
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: linux-amd64
type: kubernetes

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: rust:1.46
  resources:
    requests:
      cpu: 1000
      memory: 200MiB
    limits:
      cpu: 2000
      memory: 200MiB
  commands:
  - USER=root cargo new --bin vaultwarden_ldap
  - cd vaultwarden_ldap
  - cp ../Cargo.toml ../Cargo.lock ./
  - cargo build --locked --release
  - rm ./target/release/deps/vaultwarden_ldap*
  - cp -r ../src src
  - cargo build --release
  - cp target/release/vaultwarden_ldap ../vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
  - sha512sum ../vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH} > ../sha512sum-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.txt

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_public_token
    files:
    - vaultwarden_ldap-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    title: ${DRONE_TAG}
    note: 'LDAP addon for Vaultwarden, version ${DRONE_TAG}'
  when:
    ref:
    - refs/tags/*

- name: checkout custom dockerfile
  image: alpine/git
  commands:
  - git fetch --no-tags origin ikaruswill/arm-docker:refs/remotes/origin/ikaruswill/arm-docker
  - git checkout origin/ikaruswill/arm-docker Dockerfile_custom

- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: Dockerfile_custom
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: amd64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: generate manifest
  image: alpine
  environment:
    IMAGE: ${DRONE_REPO_NAME}
  commands:
  - |
    wget -qO - https://raw.githubusercontent.com/ikaruswill/drone-manifests/master/manifest.tmpl \
    | sed -e "s/\$${IMAGE}/$${IMAGE}/" > manifest.tmpl

- name: push manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm64
    - linux/amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- linux-arm64
- linux-amd64

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password
---
kind: secret
name: github_release_public_token
get:
  path: drone-secrets
  name: github_release_public_token